# Generated by Django 5.1 on 2024-09-03 02:52

import django.db.models.deletion
import home.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, default='Uh...Earth?', help_text='Do you want to fill this out? :D', max_length=255, null=True, verbose_name='Location: ')),
                ('quote', models.CharField(blank=True, help_text="'Pampa-Angas'", max_length=300, verbose_name='Quote you live by: ')),
                ('about_me', models.TextField(blank=True, default='...Default About Me text', help_text='Tell us something about you.')),
                ('image', models.ImageField(blank=True, default='defaults/round.png', help_text='Help us recognize you. ;)', upload_to=home.models.Profile.dp_directory_path, verbose_name='Profile Picture: ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
